Models/Stock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace dotnet.Models
{
    public class Stock
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        public string? Symbol { get; set; }
        [Required]
        public DateOnly Date { get; set; }
        [Required]
        public float CloseorLast { get; set; }
        [Required] 
        public int Volume { get; set; }
        [Required]
        public float Open { get; set; }
        [Required]
        public float High { get; set; }
        [Required]
        public float Low { get; set; }
    }
}

Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using dotnet.Data;
using dotnet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Newtonsoft.Json;

namespace dotnet.Controllers
{
    public class StocksController : Controller
    {
        private readonly ApplicationDbContext _db;
        private IEnumerable<Stock> savedObj;

        public StocksController(ApplicationDbContext db)
        {
            this._db=db;
        }
        public IActionResult Index()
        {
            IEnumerable<Stock?> obj= _db.Stocks!.OrderByDescending(y=>y.Date.Year).ThenByDescending(m=>m.Date.Month).ThenByDescending(d=>d.Date.Day).GroupBy(g=>g.Name).Select(g=>g.FirstOrDefault());
            return View(obj);
        }
        [Authorize]
        public IActionResult Detail(string? Symbol){
            
            IEnumerable<Stock> obj= _db.Stocks!.OrderByDescending(y=>y.Date.Year).ThenByDescending(m=>m.Date.Month).ThenByDescending(d=>d.Date.Day).Where(n=> n.Symbol==Symbol).Take(10);
            savedObj=obj;
            return View(obj);
        }
        
         /*  [Authorize]
        public IActionResult Predict(string? Symbol){
            
            IEnumerable<Stock?> obj= _db.Stocks!.OrderByDescending(y=>y.Date.Year).ThenByDescending(m=>m.Date.Month).ThenByDescending(d=>d.Date.Day).GroupBy(g=>g.Name).Select(g=>g.FirstOrDefault());
            return View(obj);
        }*/

        [Authorize(Roles ="admin,superuser")]
        //[HttpPost]
        
        public async Task<IActionResult> Predict(string Symbol){
            

            var payload= new 
            {
                name=Symbol,
            };


            using (var client = new HttpClient())
            {

                var response=client.PostAsJsonAsync("http://localhost:5000/prediction",payload);
                
                
                var something= await response.Result.Content.ReadFromJsonAsync<Prediction>();
            
                float price=float.Parse(something.prediction,CultureInfo.InvariantCulture.NumberFormat);
            
                IEnumerable<Stock> obj= _db.Stocks!.OrderByDescending(y=>y.Date.Year).ThenByDescending(m=>m.Date.Month).ThenByDescending(d=>d.Date.Day).Where(n=> n.Symbol==Symbol).Take(10);

                int vol=0;

                foreach (var item in obj)
                {
                    vol+=item.Volume;
                }

                vol=(vol/10);

                Stock newObj= new Stock();
                newObj.CloseorLast=price;
                newObj.High=price;
                newObj.Low=price;
                newObj.Date=DateOnly.FromDateTime(DateTime.Now);
                newObj.Open=price;
                newObj.Symbol=Symbol;
                newObj.Name=obj.ElementAt(0).Name;
                newObj.Volume=vol;
                
                await _db.Stocks.AddAsync(newObj);
                await _db.SaveChangesAsync();


                //return Ok(something.prediction);

                return View(obj);
            }
            
        }

        [Authorize]
        public IActionResult Graph(string? Symbol,int nod)
        {
            IEnumerable<Stock> obj= _db.Stocks!.OrderByDescending(y=>y.Date.Year).ThenByDescending(m=>m.Date.Month).ThenByDescending(d=>d.Date.Day).Where(n=> n.Symbol==Symbol).Take(nod);
            
            ViewBag.TotalLength=_db.Stocks!.Where(w=>w.Symbol==Symbol).Count();

            List<DataPoint> dataPoints = new List<DataPoint>();
            
       
            

            foreach(var element in obj)
            {
                var date = element.Date;
                var day = date.Day;
                var month = date.Month;
                var year = date.Year;

                var d = new DateTime(year, month, day);
                var baseDate = new DateTime (1970, 01, 01);
                var numberOfSeconds = (Int64)d.Subtract(baseDate).TotalSeconds*1000; //*1000000

                var value =  (Int32)element.CloseorLast;
                dataPoints.Add(new DataPoint(numberOfSeconds, value));

            }
            ViewBag.Name = obj.ElementAt(0).Name;
            
            var a = JsonConvert.SerializeObject(dataPoints);
            ViewBag.DataPoints = a;
            return View(obj);

        }
    }
}

Views/Stocks/Detail.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;
@model IEnumerable<Stock>
@{
    ViewData["Title"] = @Model.First().Name;
}

<div class='containrer p-3'>
    <div class= "row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Model.First().Name</h2>
        </div>
        <div class="col-6 text-end">
            @if(signInManager.IsSignedIn(User) && (User.IsInRole("admin") || User.IsInRole("superuser") )) {
                <a asp-controller="Stocks" asp-action="Predict" asp-route-Symbol="@Model.First().Symbol" class="btn btn-primary" style="width:150px">Predict</a> }
                <a asp-controller="Stocks" asp-action="Graph" asp-route-Symbol="@Model.First().Symbol" asp-route-nod=30 class="btn btn-primary" style="width: 150px;">Show Graph</a>
            <a asp-controller="Stocks" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Date
                </th>
                <th>
                    Volume
                </th>
                <th>
                    Price
                </th>

            </tr>
        </thead>
        <tbody>
            
             @foreach (var obj in Model)
            {
                <tr>
                    <td width="30%">
                        @obj.Date
                    </td>
                    <td width="30%">
                        @obj.Volume.ToString("N0")
                    </td>
                    <td width="20%">
                        @string.Concat("$"+obj.CloseorLast.ToString())
                    </td>
                </tr>
            }
        </tbody> 
    </table>
    
</div>

Views/Stocks/Graph.cshtml
@model IEnumerable<Stock>
@{
    ViewData["Title"] = @Model.First().Name;
}
 

<div class='containrer p-3'>
    <div class= "row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Model.First().Name</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Stocks" asp-action="Detail" asp-route-Symbol="@Model.First().Symbol" class="btn btn-secondary" style="width:150px">Back</a>
        </div>
    </div>


<!DOCTYPE HTML>
<html>
<head>
<script>
window.onload = function () {
 
var dataPoints = [];
var chart = new CanvasJS.Chart("chartContainer", {

	animationEnabled: true,
	theme: "dark1",
	backgroundColor: null,

	axisY: {
		title: "USD",
		titleFontSize: 24,
		prefix: "$",
		crosshair: {
			enabled: true,
			valueFormatString: "$#,##0.##",
			snapToDataPoint: true
		}
	},
	axisX: {
		crosshair: {
			enabled: true,
			snapToDataPoint: true
		}
	},
	data: [{
		type: "line",
		yValueFormatString: "$#,##0.##",
		 xValueType: "dateTime",
		//dataPoints: dataPoints
        dataPoints: @Html.Raw(ViewBag.DataPoints)
	}]
});
chart.render();

}
</script>
</head>
<body>
<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
<script src="https://canvasjs.com/assets/script/jquery.canvasjs.min.js"></script>
</body>
</html>     

<div class='containrer p-3'>
    <div class= "col pt-4 text-center">
			    <a asp-controller="Stocks" asp-action="Graph" asp-route-Symbol="@Model.First().Symbol" asp-route-nod=30 class="btn btn-tertiary" >1 Month</a>
				<a asp-controller="Stocks" asp-action="Graph" asp-route-Symbol="@Model.First().Symbol" asp-route-nod=90 class="btn btn-tertiary" >3 Months</a>
				<a asp-controller="Stocks" asp-action="Graph" asp-route-Symbol="@Model.First().Symbol" asp-route-nod=180 class="btn btn-tertiary" >6 Months</a>
				<a asp-controller="Stocks" asp-action="Graph" asp-route-Symbol="@Model.First().Symbol" asp-route-nod=365 class="btn btn-tertiary" >1 Year</a>
				<a asp-controller="Stocks" asp-action="Graph" asp-route-Symbol="@Model.First().Symbol" asp-route-nod=1095 class="btn btn-tertiary" >3 Years</a>
				<a asp-controller="Stocks" asp-action="Graph" asp-route-Symbol="@Model.First().Symbol" asp-route-nod="@ViewBag.TotalLength" class="btn btn-tertiary" >All Time</a></div>
		</div>
    </div>

Views/Stocks/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;
@model IEnumerable<Stock>
@{
    ViewData["Title"] = "Stocks";
}

<div class='containrer p-3'>
    <div class= "row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Stocks</h2>
        </div>
        <div class="col-6 text-end">
            </a>
        </div>
    </div>


    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Symbol
                </th>
                <th>
                    Date
                </th>
                <th>
                    Volume
                </th>
                <th>
                    Price
                </th>
                <th>
                    Detail
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="40%">
                        @obj.Name
                    </td>
                    <td width="10%">
                        @obj.Symbol
                    </td>
                    <td width="15%">
                        @obj.Date
                    </td>
                    <td width="20%">
                        @obj.Volume.ToString("N0")
                    </td>
                    <td width="15%">
                        @string.Concat("$"+obj.CloseorLast.ToString())
                    </td>
                    <td>
                        @if(signInManager.IsSignedIn(User)) {
                        <a asp-controller="Stocks" asp-action="Detail" asp-route-Symbol="@obj.Symbol">Detail</a> }
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

Views/Stocks/Predict.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;
@model IEnumerable<Stock>
@{
    ViewData["Title"] = @Model.First().Name;
}

<div class='containrer p-3'>
    <div class= "row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Model.First().Name</h2>
        </div>
        <div class="col-6 text-end">
            <h1>Prediction Successfull</h1>
            <a asp-controller="Stocks" asp-action="Detail"  asp-route-Symbol="@Model.First().Symbol" class="btn btn-secondary" style="width:150px">Back</a>
        </div>
    </div>

</div>